Add sqlx
efectn/go-orm-benchmarks pull request #10
Opened 2022-04-24 17:59 UTC by gandaldf

To support MultiInsert I used `NamedExec`(as per https://github.com/jmoiron/sqlx/issues/134)

2022-04-24 18:46 UTC, efectn commented on benchs/sqlx.go
> +const (
I think we can use https://github.com/efectn/go-orm-benchmarks/blob/master/benchs/raw.go#L10 here.

2022-04-24 18:49 UTC, efectn commented on benchs/sqlx.go
> +const (
To make code shorter and cleaner.

2022-04-24 18:50 UTC, efectn requested changes
Don't forget adding sqlx to README

2022-04-25 09:45 UTC, gandaldf commented on benchs/sqlx.go
> +const (
> I think we can use https://github.com/efectn/go-orm-benchmarks/blob/master/benchs/raw.go#L10 here.

If you look closely the constants are slightly different (I changed the last two and added two more), so for the sake of readability I prefered let them in their own file making a little copy.

2022-04-25 09:46 UTC, gandaldf commented
Pushed README update!

2022-04-25 09:54 UTC, efectn commented on benchs/sqlx.go
> +const (
Right, sorry

2022-04-25 09:59 UTC, efectn approved these changes

2022-04-25 09:59 UTC, merged